### ISSUE TITLE
NameError: name '_flatten_plus_safe' is not defined

### ISSUE THREAD

**Issue by sarah872** [BigelowLab/sag-mg-recruit#17]
I am running the `sag_mg_recruit.py` as such:

```
python sag-mg-recruit/sag_mg_recruit.py --checkm False --log run1_2019-12-17.log --cores 8 --outdir run1_2019-12-17 mg_table sag_table 
```

But I am getting the following error:

```
Traceback (most recent call last):
  File "sag-mg-recruit/sag_mg_recruit.py", line 1241, in <module>
    main()
  File "/home/user/py3-venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/py3-venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/py3-venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/py3-venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "sag-mg-recruit/sag_mg_recruit.py", line 1166, in main
    mgtbl = process_multi_mgs(input_mg_table, mgdir, threads=cores, mmd=mmd, mino=mino, maxo=maxo, minlen=minlen)
  File "sag-mg-recruit/sag_mg_recruit.py", line 445, in process_multi_mgs
    joined_fq = join(n, f, fq2=r, threads=threads, mmd=mmd, mino=mino, maxo=maxo, outdir=outdir)
  File "sag-mg-recruit/sag_mg_recruit.py", line 389, in join
    max_overlap=maxo, cores=threads)
  File "sag-mg-recruit/sag_mg_recruit.py", line 198, in run_flash
    with file_transaction(outfiles) as tx_outfiles:
  File "/apps/python3/3.7.0/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "sag-mg-recruit/sag_mg_recruit.py", line 56, in file_transaction
    safe_names, orig_names = _flatten_plus_safe(rollback_files)
NameError: name '_flatten_plus_safe' is not defined
```

The installation seems to have worked, also all the dependencies (flash/bwa/samtools/bedtools) are in `PATH`.

This is the `log` file:
```
INFO:__main__:None
INFO:__main__:processing the metagenomes
```

**Comment by juliambrosman** [comment]
Thanks for submitting an issue.  The latest commit should resolve this.  

As a side note, it looks like you're using python 3.7, I wrote it for python 2.7 and have never tested it with 3.7 so you may (or may not) run into problems because of this.
