### ISSUE TITLE
AttributeError: 'module' object has no attribute 'FastxFile'

### ISSUE THREAD

**Issue by sarah872** [BigelowLab/sag-mg-recruit#18]
Coming from issue https://github.com/BigelowLab/sag-mg-recruit/issues/17 (thanks for resolving!), a new error was thrown:

```
input_mg_table = mg_table
input_sag_table = sag_table
outdir = run1_2019-12-17
cores = 8
mmd = 0.05
mino = 35
maxo = 150
minlen = 150
pctid = 95
overlap = 0
log = run1_2019-12-17.log
concatenate = True
checkm=False
Traceback (most recent call last):
  File "sag-mg-recruit/sag_mg_recruit.py", line 1290, in <module>
    main()
  File "/home/user/00_scripts/py2-venv/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/00_scripts/py2-venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/00_scripts/py2-venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/00_scripts/py2-venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "sag-mg-recruit/sag_mg_recruit.py", line 1215, in main
    mgtbl = process_multi_mgs(input_mg_table, mgdir, threads=cores, mmd=mmd, mino=mino, maxo=maxo, minlen=minlen)
  File "sag-mg-recruit/sag_mg_recruit.py", line 490, in process_multi_mgs
    joined_fq = join(n, f, fq2=r, threads=threads, mmd=mmd, mino=mino, maxo=maxo, outdir=outdir)
  File "sag-mg-recruit/sag_mg_recruit.py", line 438, in join
    joined, reads = join_stats(histin, fq1, fastq2=fq2, prefix=prefix, outdir=outdir)
  File "sag-mg-recruit/sag_mg_recruit.py", line 301, in join_stats
    original_count = read_count(fastq1, outdir)[0]
  File "sag-mg-recruit/sag_mg_recruit.py", line 324, in read_count
    for name, seq, qual in readfx(fname):
  File "sag-mg-recruit/sag_mg_recruit.py", line 204, in readfx
    fx = pysam.FastxFile(fastx)
AttributeError: 'module' object has no attribute 'FastxFile'
```

**Comment by juliambrosman** [comment]
Is it possible that you are using an older version of pysam?  Updating that might solve your issue.  The FastxFile function was added to pysam in release pysam-0.8.2

**Comment by sarah872** [comment]
thank you, should have checked!
